insert into CATEGORIES (categoryId, language, description) values (1, 'Bootstrap', 'Webpages');
insert into CATEGORIES (categoryId, language, description) values (2, 'JavaScript', 'Articles');
insert into CATEGORIES (categoryId, language, description) values (3, 'Kotlin', 'Videos');
insert into CATEGORIES (categoryId, language, description) values (4, 'Elixir', 'Programs');
insert into CATEGORIES (categoryId, language, description) values (5, 'Go', 'Cheat sheets');
insert into CATEGORIES (categoryId, language, description) values (6, 'Pandas', 'Interactive coding exercises');
insert into CATEGORIES (categoryId, language, description) values (7, 'ASP.NET Core', 'Code snippets');
insert into CATEGORIES (categoryId, language, description) values (8, 'Bootstrap', 'E-books');
insert into CATEGORIES (categoryId, language, description) values (9, 'Bootstrap', 'Podcasts');
insert into CATEGORIES (categoryId, language, description) values (10, 'FastAPI', 'Courses');
insert into CATEGORIES (categoryId, language, description) values (11, 'Bun', 'Documentation');
insert into CATEGORIES (categoryId, language, description) values (12, 'Go', 'Workshops');
insert into CATEGORIES (categoryId, language, description) values (13, 'Foundation', 'GitHub repositories');
insert into CATEGORIES (categoryId, language, description) values (14, 'ASP.NET Core', 'Forums');
insert into CATEGORIES (categoryId, language, description) values (15, 'Kotlin', 'Infographics');
insert into CATEGORIES (categoryId, language, description) values (16, 'Svelte', 'Newsletters');
insert into CATEGORIES (categoryId, language, description) values (17, 'Python', 'Whitepapers');
insert into CATEGORIES (categoryId, language, description) values (18, 'ASP.NET Core', 'Roadmaps');
insert into CATEGORIES (categoryId, language, description) values (19, 'Angular', 'Open-source tools');
insert into CATEGORIES (categoryId, language, description) values (20, 'FastAPI', 'Design patterns');
insert into CATEGORIES (categoryId, language, description) values (21, 'Objective-C', 'DevOps scripts');
insert into CATEGORIES (categoryId, language, description) values (22, 'FastAPI', 'Security guides');
insert into CATEGORIES (categoryId, language, description) values (23, 'Vue.js', 'Testing frameworks');
insert into CATEGORIES (categoryId, language, description) values (24, 'Svelte', 'Command-line tools');
insert into CATEGORIES (categoryId, language, description) values (25, 'ASP.NET Core', 'Cloud computing resources');
insert into CATEGORIES (categoryId, language, description) values (26, 'Elixir', 'Machine learning models');
insert into CATEGORIES (categoryId, language, description) values (27, 'Bootstrap', 'Community-driven tutorials');
insert into CATEGORIES (categoryId, language, description) values (28, 'Elixir', 'Live coding sessions');
insert into CATEGORIES (categoryId, language, description) values (29, 'PyTorch', 'Online coding challenges');
insert into CATEGORIES (categoryId, language, description) values (30, 'Astro', 'Webpages');
insert into CATEGORIES (categoryId, language, description) values (31, 'Elixir', 'Articles');
insert into CATEGORIES (categoryId, language, description) values (32, 'PHP', 'Videos');
insert into CATEGORIES (categoryId, language, description) values (33, 'Foundation', 'Programs');
insert into CATEGORIES (categoryId, language, description) values (34, 'jQuery', 'Cheat sheets');
insert into CATEGORIES (categoryId, language, description) values (35, 'Objective-C', 'Interactive coding exercises');
insert into CATEGORIES (categoryId, language, description) values (36, 'Angular', 'Code snippets');
insert into CATEGORIES (categoryId, language, description) values (37, 'Elixir', 'E-books');
insert into CATEGORIES (categoryId, language, description) values (38, 'Go', 'Podcasts');
insert into CATEGORIES (categoryId, language, description) values (39, 'Python', 'Courses');
insert into CATEGORIES (categoryId, language, description) values (40, 'Scala', 'Documentation');
insert into CATEGORIES (categoryId, language, description) values (41, 'Dart', 'Workshops');
insert into CATEGORIES (categoryId, language, description) values (42, 'Astro', 'GitHub repositories');
insert into CATEGORIES (categoryId, language, description) values (43, 'Express.js', 'Forums');
insert into CATEGORIES (categoryId, language, description) values (44, 'TensorFlow', 'Infographics');
insert into CATEGORIES (categoryId, language, description) values (45, 'Ruby on Rails', 'Newsletters');
insert into CATEGORIES (categoryId, language, description) values (46, 'C++', 'Whitepapers');
insert into CATEGORIES (categoryId, language, description) values (47, 'C++', 'Roadmaps');
insert into CATEGORIES (categoryId, language, description) values (48, 'Laravel', 'Open-source tools');
insert into CATEGORIES (categoryId, language, description) values (49, 'Scala', 'Design patterns');
insert into CATEGORIES (categoryId, language, description) values (50, 'C++', 'DevOps scripts');
insert into CATEGORIES (categoryId, language, description) values (51, 'Objective-C', 'Security guides');
insert into CATEGORIES (categoryId, language, description) values (52, 'Phoenix', 'Testing frameworks');
insert into CATEGORIES (categoryId, language, description) values (53, 'PyTorch', 'Command-line tools');
insert into CATEGORIES (categoryId, language, description) values (54, 'Rust', 'Cloud computing resources');
insert into CATEGORIES (categoryId, language, description) values (55, 'Astro', 'Machine learning models');
insert into CATEGORIES (categoryId, language, description) values (56, 'NumPy', 'Community-driven tutorials');
insert into CATEGORIES (categoryId, language, description) values (57, 'Scala', 'Live coding sessions');
insert into CATEGORIES (categoryId, language, description) values (58, 'Bootstrap', 'Online coding challenges');
insert into CATEGORIES (categoryId, language, description) values (59, 'SolidJS', 'Webpages');
insert into CATEGORIES (categoryId, language, description) values (60, 'Flask', 'Articles');
